
## 1.
Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. 
Specifically, when increasing is False, the i-th output column is the input vector 
raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [28]:
import numpy as np



In [29]:

# According to Vandermonde matrix, considering the increasing =False
# Making each row of the array as a list by applying Geometric Progression
# the output array will be of the order len(input_array) X len(input_array) 4X4 in this case
# lets make 4 lists as rows of the output matrix and then print in the required form



def vander_output ( input, increasing=False):
    N=input.size
    matr = np.zeros([N,N])
    
    if increasing ==False:
        matr = np.row_stack([list(j **(N-i-1) for i in range(N)) for j in input])
    elif increasing == True:
        matr = np.row_stack([list(j **(i) for i in range(N)) for j in input])
      
    return matr

##################################################################################################

input_array = np.array([1,2,3,5])

vander_mat = vander_output(input_array,False)
print("The Required array is when increasing is False:")
print(vander_mat)

vander_mat = vander_output(input_array,True)
print("The Required array is when increasing is True:")
print(vander_mat)

The Required array is when increasing is False:
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
The Required array is when increasing is True:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


The above results can be tested using np.vendor metho as follows

In [32]:
#with increasing = False(default behaviour)
np.vander(input_array)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [34]:
#with increasing = True
np.vander(input_array,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

###############################################################################################################



## 2
Write a function to find moving average in an array over a window:
  
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [27]:
def moving_avg(seq_array,k):
    
    n= seq_array.size
    elements = n-k+1
    i = 0
    avg_list = []
    avg = np.zeros([1,elements])
    avg  = np.row_stack([round(np.sum(seq_array[i:i+k:1])/k ,2) for i in range(0,elements)])
    print(type(avg))
    return avg

##############################################################################################
given_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] )
window = 3
avergae_array = moving_avg(given_array,window)
print("The requied vector of moving averages of the given array :")
print(avergae_array)



<class 'numpy.ndarray'>
The requied vector of moving averages of the given array :
[[  5.  ]
 [  4.67]
 [  5.67]
 [  6.67]
 [  9.67]
 [ 28.67]
 [ 49.33]
 [ 72.67]
 [ 84.  ]
 [ 93.33]
 [116.33]]
